Fix compatibility with JSON.generate/dump
3757c98ab5927477ca75d1dff28d896ea2d42dae introduced a NoMethodError: undefined method `delete' for #<JSON::Ext::Generator::State:0x00007f8718ddded8> when serializing via these JSON gem methods.