rename currency column in tests
avoid using `currency` as the name of the currency column to avoid having this column match the name of variables, and prevent test passing when they should not. This regression test now fails
```
     NameError:
       undefined local variable or method 'currency' for an instance of MoneyWithReadOnlyCurrency
```